import type { Claim, User } from './types';

export const mockUser: User = {
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  avatarUrl: 'https://placehold.co/100x100.png',
};

export const mockClaims: Claim[] = [
  {
    id: 'CLM-001',
    policyNo: 'POL-12345',
    amount: 1250.75,
    description: 'Minor fender bender in a parking lot. Scratches on the rear bumper.',
    submittedAt: '2023-10-26T10:00:00Z',
    status: 'Approved',
    riskScore: 12,
    riskLabel: 'Low',
    documents: [
      { name: 'accident-photo-1.jpg', url: '#', forgeryCheck: 'Passed' },
      { name: 'police-report.pdf', url: '#', forgeryCheck: 'Passed' },
    ],
    claimant: { name: 'John Smith', avatarUrl: 'https://placehold.co/100x100.png' },
    location: { lat: 34.0522, lng: -118.2437 },
    comments: [],
  },
  {
    id: 'CLM-002',
    policyNo: 'POL-67890',
    amount: 8500.0,
    description: 'Water damage from a burst pipe in the kitchen. Claim includes damage to flooring and cabinets.',
    submittedAt: '2023-10-25T14:30:00Z',
    status: 'Investigation',
    riskScore: 92,
    riskLabel: 'High',
    documents: [
      { name: 'invoice_repair.pdf', url: '#', forgeryCheck: 'Suspected' },
      { name: 'damage_photo.jpg', url: '#', forgeryCheck: 'Passed' },
    ],
    claimant: { name: 'Jane Doe', avatarUrl: 'https://placehold.co/100x100.png' },
    location: { lat: 40.7128, lng: -74.0060 },
    comments: [
        { id: '1', author: 'Investigator Mike', avatarUrl: 'https://placehold.co/100x100.png', text: 'The invoice from "Super Plumbers" looks altered. The font is inconsistent. Needs a closer look.', timestamp: '2023-10-25T15:00:00Z' },
        { id: '2', author: 'Admin Sarah', avatarUrl: 'https://placehold.co/100x100.png', text: 'Agreed. Let\'s request original documents from the claimant.', timestamp: '2023-10-25T15:05:00Z' },
    ],
  },
  {
    id: 'CLM-003',
    policyNo: 'POL-54321',
    amount: 320.5,
    description: 'Stolen bicycle from a secured garage.',
    submittedAt: '2023-10-24T09:00:00Z',
    status: 'Pending',
    riskScore: 45,
    riskLabel: 'Medium',
    documents: [{ name: 'receipt.pdf', url: '#', forgeryCheck: 'Pending' }],
    claimant: { name: 'Peter Jones', avatarUrl: 'https://placehold.co/100x100.png' },
    location: { lat: 37.7749, lng: -122.4194 },
    comments: [],
  },
  {
    id: 'CLM-004',
    policyNo: 'POL-98765',
    amount: 2100.0,
    description: 'Lost luggage during international travel.',
    submittedAt: '2023-10-22T18:45:00Z',
    status: 'Rejected',
    riskScore: 25,
    riskLabel: 'Low',
    documents: [{ name: 'airline_report.pdf', url: '#', forgeryCheck: 'Passed' }],
    claimant: { name: 'Emily White', avatarUrl: 'https://placehold.co/100x100.png' },
    location: { lat: 51.5074, lng: -0.1278 },
    comments: [],
  },
  {
    id: 'CLM-005',
    policyNo: 'POL-11223',
    amount: 15000.0,
    description: 'Claim for a stolen art piece from a home. Claimant has a history of similar claims.',
    submittedAt: '2023-10-21T11:20:00Z',
    status: 'Investigation',
    riskScore: 85,
    riskLabel: 'High',
    documents: [
      { name: 'appraisal.pdf', url: '#', forgeryCheck: 'Passed' },
      { name: 'police_report__final.pdf', url: '#', forgeryCheck: 'Passed' },
    ],
    claimant: { name: 'Chris Green', avatarUrl: 'https://placehold.co/100x100.png' },
    location: { lat: 48.8566, lng: 2.3522 },
    comments: [],
  },
];
